# This is a basic workflow to help you get started with Actions

name: CI/CD Lowkey Pro Server

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.0.0
        with:
          node-version : 16.13.1
      
      - name: Install Dependencies
        run: 
          npm install
          npm test
          
  deploy:
    runs-on : ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: AkhileshNS/heroku-deploy@v3.12.12
          with:
            # This will be used for authentication. You can find it in your heroku homepage account settings
            heroku_api_key: 99a7eadd-e512-459b-855a-01d93ac48cf0
            # Email that you use with heroku
            heroku_email: farisadam97@gmail.com
            # The appname to use for deploying/updating
            heroku_app_name: lowkey-pro-server
